# This is a basic workflow to help you get started with Actions

name: Build test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the v2019.01-jethome branch
  push:
    branches: [ v2019.01-* ]
  pull_request:
    branches: [ v2019.01-* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CROSS_COMPILE: "aarch64-elf-"
  CROSS_COMPILE_T32: "arm-eabi-"
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fix permissions
        run: sudo /usr/local/bin/fixprivileges.sh
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - name: Build for j100 v1
        run: |
          cd ${GITHUB_WORKSPACE}
          make distclean
          make axg_jethubj100_v1_defconfig
          make

      - name: Release file
        uses: djnicholson/release-action@v2.11
        with:
          # GitHub auth token
          token: ${{ secrets.GITHUBTOKEN }}
          # Name of Release to add file to
          release-name: Testing build
          # Name of the tag for the release (will be associated with current branch)
          tag-name: j100-testing 
          # Name for the asset
          asset-name: u-boot.bin
          # File to release
          file: u-boot.bin
